### ISSUE TITLE
Dropdown menu button too wide

### ISSUE THREAD

**Issue by jonachehilton** [cp3402-students/cp3402-2021-site-cp3402-2021-team01#29]
Thoughts gents? @callumgedling @JakeSmith01 @cvtorrisi93

**Comment by JakeSmith01** [comment]
I agree, @callumgedling @cvtorrisi93 Any chance we can make the drop down in the menu smaller?

**Comment by cvtorrisi93** [comment]
Updated the dropdown menu width. Closing issue.
